name: Pull Request Notify

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Discord PR created
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: "📢 New PR: ${{ github.event.pull_request.title }}\nBy: ${{ github.actor }}\nURL: ${{ github.event.pull_request.html_url }}"
