name: Pull Request Notification

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Discord notification for PR
        uses: Ilshidur/action-discord@master
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          message: "📢 New Pull Request: ${{ github.event.pull_request.title }} by ${{ github.actor }}\n${{ github.event.pull_request.html_url }}"
